{
 "title": "Global",
 "description": "Kubernetes Dashboard - a fork from dotdc/grafana-dashboards-kubernetes/k8s-views-global.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_node_info,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\", region=~\"$region\"},cluster_id)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},env)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_cpu_time_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)\n/\nsum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)\n/\nsum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  k8s_node_memory_usage_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)\n/\nsum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)\n/\nsum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)\n/\nsum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  count by (node) (\n    kube_node_info{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }\n  )\n)"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "stat",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_status_running{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(\n  kube_service_info{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(\n  kube_endpoint_info{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(\n  kube_ingress_info{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(\n  kube_deployment_labels{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(\n  kube_statefulset_labels{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(\n  kube_daemonset_labels{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(\n  kube_persistentvolumeclaim_info{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(\n  kube_horizontalpodautoscaler_info{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(\n  kube_configmap_info{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(\n  kube_secret_info{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(\n  kube_networkpolicy_labels{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Network Policies"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  kube_namespace_created{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_cpu_time_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      cell_id=~\"$cell_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  k8s_node_memory_usage_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{\n    phase=\"Running\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU  Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_cpu_time_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  k8s_node_memory_usage_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)\n/\nsum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "CPU Utilization by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_time_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_namespace_name)",
     "legendFormat": "{{ k8s_namespace_name }}"
    }
   ]
  },
  {
   "title": "RAM Utilization by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (k8s_namespace_name)",
     "legendFormat": "{{ k8s_namespace_name }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_cpu_time_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_node_name)\n/\nsum(\n  label_replace(\n    kube_node_status_capacity{\n      resource=\"cpu\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    },\n    \"k8s_node_name\",\n    \"$1\",\n    \"node\",\n    \"(.+)\"\n  )\n) by (k8s_node_name)",
     "legendFormat": "{{ k8s_node_name }}"
    }
   ]
  },
  {
   "title": "RAM Utilization by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  k8s_node_memory_usage_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (k8s_node_name)",
     "legendFormat": "{{ k8s_node_name }}"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds by Namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_cfs_throttled_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_namespace_name) > 0",
     "legendFormat": "{{ k8s_namespace_name }}"
    }
   ]
  },
  {
   "title": "CPU Core Throttled by Node",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    node_cpu_core_throttles_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_node_name)",
     "legendFormat": "{{ k8s_node_name }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Kubernetes Pods QoS Classes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_qos_class{\n    app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n  }\n) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    {
     "expr": "sum(\n  kube_pod_info{\n    app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }\n  )",
     "legendFormat": "Total pods"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_reason{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "OOM Events by Namespace",
   "type": "table",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    container_oom_events_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_namespace_name) > 0",
     "legendFormat": "{{ k8s_namespace_name }}"
    }
   ]
  },
  {
   "title": "Container Restarts by Namespace",
   "type": "table",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    kube_pod_container_status_restarts_total{\n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Network I/O by Device",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"receive\",\n      interface!~\"(veth|azv|lxc).*\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (interface)",
     "legendFormat": "Input : {{ interface }}"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"transmit\",\n      interface!~\"(veth|azv|lxc).*\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (interface)",
     "legendFormat": "Output : {{ interface }}"
    }
   ]
  },
  {
   "title": "Network Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_network_errors_total{\n      direction=\"receive\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Input"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_node_network_errors_total{\n      direction=\"transmit\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Network I/O by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_pod_network_io_bytes_total{\n      direction=\"receive\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_namespace_name)",
     "legendFormat": "Input : {{ k8s_namespace_name }}"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_pod_network_io_bytes_total{\n      direction=\"transmit\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_namespace_name)",
     "legendFormat": "Output : {{ k8s_namespace_name }}"
    }
   ]
  },
  {
   "title": "Network I/O (with all virtual devices) by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"receive\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_node_name)",
     "legendFormat": "Input : {{ k8s_node_name }}"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"transmit\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_node_name)",
     "legendFormat": "Output : {{ k8s_node_name }}"
    }
   ]
  },
  {
   "title": "Network I/O (without loopback)  by Node",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"receive\",\n      interface!~\"(veth|azv|lxc|lo).*\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_node_name)",
     "legendFormat": "Input : {{ k8s_node_name }}"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"transmit\",\n      interface!~\"(veth|azv|lxc|lo).*\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_node_name)",
     "legendFormat": "Output : {{ k8s_node_name }}"
    }
   ]
  },
  {
   "title": "Network Received (loopback only) by Node",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"receive\",\n      interface=\"lo\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_node_name)",
     "legendFormat": "Input : {{ k8s_node_name }}"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"transmit\",\n      interface=\"lo\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_node_name)",
     "legendFormat": "Output : {{ k8s_node_name }}"
    }
   ]
  }
 ]
}