{
 "title": "Namespaces",
 "description": "Kubernetes Dashboard - a fork from dotdc/grafana-dashboards-kubernetes/k8s-views-namespaces.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_node_info,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\", region=~\"$region\"},cluster_id)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},env)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", env=~\"$env\"},namespace)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace(s) Usage on Total Custer CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_time_seconds_total{\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) / sum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "Namespace(s) Usage on Total Cluster RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    k8s_namespace_name=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) / sum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_info{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(\n  kube_service_info{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(\n  kube_ingress_info{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(\n  kube_deployment_labels{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(\n  kube_statefulset_labels{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(\n  kube_daemonset_labels{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(\n  kube_persistentvolumeclaim_info{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(\n  kube_hpa_labels{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(\n  kube_configmap_info{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(\n  kube_secret_info{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(\n  kube_networkpolicy_labels{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Network Policies"
    }
   ]
  },
  {
   "title": "Namespace(s) CPU Usage (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_time_seconds_total{\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Cluster Total"
    }
   ]
  },
  {
   "title": "Namespace(s) RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    k8s_namespace_name=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Cluster Total"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_time_seconds_total{\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_pod_name)",
     "legendFormat": "{{ k8s_pod_name }}"
    }
   ]
  },
  {
   "title": "RAM Utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    k8s_namespace_name=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (k8s_pod_name)",
     "legendFormat": "{{ k8s_pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_cfs_throttled_seconds_total{\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_pod_name) > 0",
     "legendFormat": "{{ k8s_pod_name }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_qos_class{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    {
     "expr": "sum(\n  kube_pod_info{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Total pods"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_reason{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "OOM Events by Pod",
   "type": "table",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    container_oom_events_total{\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_namespace_name, k8s_pod_name) > 0",
     "legendFormat": "{{ k8s_pod_name }}"
    }
   ]
  },
  {
   "title": "Container Restarts by Pod",
   "type": "table",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    kube_pod_container_status_restarts_total{\n      namespace=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (namespace, pod) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of Pods by State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_status_ready{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(\n  kube_pod_container_status_running{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(\n  kube_pod_container_status_waiting{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(\n  kube_pod_container_status_restarts_total{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Restarts Total"
    },
    {
     "expr": "sum(\n  kube_pod_container_status_terminated{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Terminated"
    }
   ]
  },
  {
   "title": "Number of Containers by Pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_info{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replicas Available by Deployment",
   "type": "stat",
   "description": "Works only for deployments",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_deployment_status_replicas_available{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Replicas Unavailable by Deployment",
   "type": "stat",
   "description": "Works only for deployments",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_deployment_status_replicas_unavailable{\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Persistent Volumes Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  max(\n    k8s_volume_capacity_bytes{\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }\n  ) by (k8s_namespace_name, k8s_volume_name)\n  -\n  max(\n    k8s_volume_available_bytes{\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }\n  ) by (k8s_namespace_name, k8s_volume_name)\n) / max(\n  k8s_volume_capacity_bytes{\n    k8s_namespace_name=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (k8s_namespace_name, k8s_volume_name)",
     "legendFormat": "{{ k8s_namespace_name }} - {{ k8s_volume_name }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes Capacity and Utilization",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  k8s_volume_capacity_bytes{\n    k8s_namespace_name=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (k8s_namespace_name, k8s_volume_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\n  k8s_volume_capacity_bytes{\n    k8s_namespace_name=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (k8s_namespace_name, k8s_volume_name) - max(\n  k8s_volume_available_bytes{\n    k8s_namespace_name=~\"$namespace\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (k8s_namespace_name, k8s_volume_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Network I/O by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_pod_network_io_bytes_total{\n      direction=\"receive\",\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_pod_name)",
     "legendFormat": "Input : {{ k8s_pod_name }}"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_pod_network_io_bytes_total{\n      direction=\"transmit\",\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_pod_name)",
     "legendFormat": "Output : {{ k8s_pod_name }}"
    }
   ]
  },
  {
   "title": "Network Packets Dropped by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_pod_network_errors_total{\n      direction=\"receive\",\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_pod_name)",
     "legendFormat": "Input {{ k8s_pod_name }}"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_pod_network_errors_total{\n      direction=\"transmit\",\n      k8s_namespace_name=~\"$namespace\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_pod_name)",
     "legendFormat": "Output {{ k8s_pod_name }}"
    }
   ]
  }
 ]
}