{
 "title": "Nodes",
 "description": "Kubernetes Dashboard - a fork from dotdc/grafana-dashboards-kubernetes/k8s-system-api-server.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_node_info,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\", region=~\"$region\"},cluster_id)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},env)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", env=~\"$env\"},node)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_cpu_time_seconds_total{\n      k8s_node_name=\"$node\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) / sum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    node=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  k8s_node_memory_usage_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) / sum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    node=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "List of Pods on Node ($node)",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{\n  node=\"$node\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_cpu_time_seconds_total{\n      k8s_node_name=\"$node\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    resource=\"cpu\",\n    node=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  k8s_node_memory_usage_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    resource=\"memory\",\n    node=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_info{\n    node=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_cpu_time_seconds_total{\n      k8s_node_name=\"$node\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k8s_node_memory_usage_bytes{\n  k8s_node_name=\"$node\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "kube_node_status_capacity{\n  resource=\"memory\",\n  node=\"$node\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "k8s_node_memory_working_set_bytes{\n  k8s_node_name=\"$node\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "RAM Working Set"
    },
    {
     "expr": "k8s_node_memory_rss_bytes{\n  k8s_node_name=\"$node\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "RAM RSS"
    },
    {
     "expr": "k8s_node_memory_available_bytes{\n  k8s_node_name=\"$node\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "RAM Available"
    }
   ]
  },
  {
   "title": "CPU Utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_time_seconds_total{\n      k8s_node_name=\"$node\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_pod_name)",
     "legendFormat": "{{ k8s_pod_name }}"
    }
   ]
  },
  {
   "title": "RAM Utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (k8s_pod_name)",
     "legendFormat": "{{ k8s_pod_name }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"receive\",\n      k8s_node_name=\"$node\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Input"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_node_network_io_bytes_total{\n      direction=\"transmit\",\n      k8s_node_name=\"$node\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Output"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max(\n  k8s_volume_capacity_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }) by (k8s_namespace_name, k8s_volume_name) - max(\n  k8s_volume_available_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }) by (k8s_namespace_name, k8s_volume_name)) / max(\n  k8s_volume_capacity_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }) by (k8s_namespace_name, k8s_volume_name)",
     "legendFormat": "{{ k8s_namespace_name }} - {{ k8s_volume_name }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Usage in GB",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  k8s_volume_capacity_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }) by (k8s_namespace_name, k8s_volume_name) - max(\n  k8s_volume_available_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }) by (k8s_namespace_name, k8s_volume_name)"
    },
    {
     "expr": "max(\n  k8s_volume_capacity_bytes{\n    k8s_node_name=\"$node\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }) by (k8s_namespace_name, k8s_volume_name)"
    }
   ]
  },
  { "title": "Node Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "FS Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(k8s_node_filesystem_usage_bytes{\n  k8s_node_name=\"$node\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n} / k8s_node_filesystem_capacity_bytes{\n  k8s_node_name=\"$node\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n})",
     "legendFormat": "Utilization"
    }
   ]
  }
 ]
}