{
 "title": "Pods",
 "description": "Kubernetes Dashboard - a fork from dotdc/grafana-dashboards-kubernetes/k8s-views-pods.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_node_info,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\", region=~\"$region\"},cluster_id)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_node_info{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},env)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", env=~\"$env\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", env=~\"$env\"},pod)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created by",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_info{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  app=~\"$app\", \n  region=~\"$region\", \n  cluster_id=~\"$cluster_id\", \n  env=~\"$env\"\n}",
     "legendFormat": "{{ created_by_kind }}: {{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Running on",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_info{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  app=~\"$app\", \n  region=~\"$region\", \n  cluster_id=~\"$cluster_id\", \n  env=~\"$env\"\n}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pod IP",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_info{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  app=~\"$app\", \n  region=~\"$region\", \n  cluster_id=~\"$cluster_id\", \n  env=~\"$env\"\n}",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  {
   "title": "QOS Class",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_qos_class{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  app=~\"$app\", \n  region=~\"$region\", \n  cluster_id=~\"$cluster_id\", \n  env=~\"$env\"\n} > 0",
     "legendFormat": "{{ qos_class }}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  app=~\"$app\", \n  region=~\"$region\", \n  cluster_id=~\"$cluster_id\", \n  env=~\"$env\"\n}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Last Terminated Exit Code",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_exitcode{\n  namespace=\"$namespace\", \n  pod=\"$pod\", \n  app=~\"$app\", \n  region=~\"$region\", \n  cluster_id=~\"$cluster_id\", \n  env=~\"$env\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Requests Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_time_seconds_total{\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) / sum(\n  kube_pod_container_resource_requests{\n    namespace=\"$namespace\",\n    pod=\"$pod\",\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=\"$namespace\",\n      pod=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "CPU Limits Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    container_cpu_time_seconds_total{\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) / sum(\n  kube_pod_container_resource_limits{\n    namespace=\"$namespace\",\n    pod=\"$pod\",\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=\"$namespace\",\n      pod=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "RAM Requests Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name=\"$pod\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) / sum(\n  kube_pod_container_resource_requests{\n    namespace=\"$namespace\",\n    pod=\"$pod\",\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=\"$namespace\",\n      pod=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "RAM Limits Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    k8s_namespace_name=\"$namespace\",\n    k8s_pod_name=\"$pod\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) / sum(\n  kube_pod_container_resource_limits{\n    namespace=\"$namespace\",\n    pod=\"$pod\",\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=\"$namespace\",\n      pod=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Resources by Container",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    resource=\"cpu\",\n    namespace=\"$namespace\", \n    pod=\"$pod\", \n    app=~\"$app\", \n    region=~\"$region\", \n    cluster_id=~\"$cluster_id\", \n    env=~\"$env\"\n  } \n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\", \n      namespace=\"$namespace\", \n      pod=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    } \n  == 1)\n) by (container)"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    resource=\"cpu\",\n    namespace=\"$namespace\", \n    pod=\"$pod\", \n    app=~\"$app\", \n    region=~\"$region\", \n    cluster_id=~\"$cluster_id\", \n    env=~\"$env\"\n  } \n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\", \n      namespace=\"$namespace\", \n      pod=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    }\n  == 1)\n) by (container)"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    resource=\"memory\", \n    namespace=\"$namespace\", \n    pod=\"$pod\", \n    app=~\"$app\", \n    region=~\"$region\", \n    cluster_id=~\"$cluster_id\", \n    env=~\"$env\"\n  } \n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\", \n      namespace=\"$namespace\", \n      pod=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    } \n  == 1)\n) by (container)"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    resource=\"memory\", \n    namespace=\"$namespace\", \n    pod=\"$pod\", \n    app=~\"$app\", \n    region=~\"$region\", \n    cluster_id=~\"$cluster_id\", \n    env=~\"$env\"\n  } \n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\", \n      namespace=\"$namespace\", \n      pod=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    } \n  == 1)\n) by (container)"
    },
    {
     "expr": "sum(\n  ${rate_func}(\n    label_replace(\n      container_cpu_time_seconds_total{\n        k8s_container_name!=\"\", \n        k8s_namespace_name=\"$namespace\", \n        k8s_pod_name=\"$pod\", \n        app=~\"$app\", \n        region=~\"$region\", \n        cluster_id=~\"$cluster_id\", \n        env=~\"$env\"\n      },\n      \"container\",\n      \"$1\",\n      \"k8s_container_name\",\n      \"(.+)\"\n    )[$__rate_interval]\n  )\n) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n  label_replace(\n    container_memory_working_set_bytes{\n      k8s_container_name!=\"\", \n      k8s_namespace_name=\"$namespace\", \n      k8s_pod_name=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    },\n    \"container\",\n    \"$1\",\n    \"k8s_container_name\",\n    \"(.+)\"\n  )\n) by (container)"
    }
   ]
  },
  {
   "title": "CPU Utilization / Requests & Limits by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    label_replace(\n      container_cpu_time_seconds_total{\n        k8s_namespace_name=\"$namespace\",\n        k8s_pod_name=\"$pod\",\n        k8s_container_name!=\"\",\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        env=~\"$env\"\n      },\n      \"container\",\n      \"$1\",\n      \"k8s_container_name\",\n      \"(.+)\"\n    )[$__rate_interval]\n  )\n) by (container) / sum(\n  kube_pod_container_resource_requests{\n    namespace=\"$namespace\",\n    pod=\"$pod\",\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=\"$namespace\",\n      pod=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n) by (container)",
     "legendFormat": "{{ container }}  REQUESTS"
    },
    {
     "expr": "sum(\n  ${rate_func}(\n    label_replace(\n      container_cpu_time_seconds_total{\n        k8s_namespace_name=\"$namespace\",\n        k8s_pod_name=\"$pod\",\n        k8s_container_name!=\"\",\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        env=~\"$env\"\n      },\n      \"container\",\n      \"$1\",\n      \"k8s_container_name\",\n      \"(.+)\"\n    )[$__rate_interval]\n  )\n) by (container) / sum(\n  kube_pod_container_resource_limits{\n    namespace=\"$namespace\",\n    pod=\"$pod\",\n    resource=\"cpu\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=\"$namespace\",\n      pod=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n) by (container)",
     "legendFormat": "{{ container }}  LIMITS"
    }
   ]
  },
  {
   "title": "RAM Utilization / Requests & Limits by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    container_memory_working_set_bytes{\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name=\"$pod\",\n      k8s_container_name!=\"\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    },\n    \"container\",\n    \"$1\",\n    \"k8s_container_name\",\n    \"(.+)\"\n  )\n) by (container) / sum(\n  kube_pod_container_resource_requests{\n    namespace=\"$namespace\",\n    pod=\"$pod\",\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=\"$namespace\",\n      pod=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n) by (container)",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum(\n  label_replace(\n    container_memory_working_set_bytes{\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name=\"$pod\",\n      k8s_container_name!=\"\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    },\n    \"container\",\n    \"$1\",\n    \"k8s_container_name\",\n    \"(.+)\"\n  )\n) by (container) / sum(\n  kube_pod_container_resource_limits{\n    namespace=\"$namespace\",\n    pod=\"$pod\",\n    resource=\"memory\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n  and on(namespace, pod) max by (namespace, pod) (\n    kube_pod_status_phase{\n      phase=\"Running\",\n      namespace=\"$namespace\",\n      pod=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } == 1\n  )\n) by (container)",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "CPU Utilization by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    label_replace(\n      container_cpu_time_seconds_total{\n        k8s_namespace_name=\"$namespace\",\n        k8s_pod_name=\"$pod\",\n        k8s_container_name!=\"\",\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        env=~\"$env\"\n      },\n      \"container\",\n      \"$1\",\n      \"k8s_container_name\",\n      \"(.+)\"\n    )[$__rate_interval]\n  )\n) by (container, id)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "RAM Utilization by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    container_memory_working_set_bytes{\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name=\"$pod\",\n      k8s_container_name!=\"\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    },\n    \"container\",\n    \"$1\",\n    \"k8s_container_name\",\n    \"(.+)\"\n  )\n) by (container, id)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    label_replace(\n      container_cpu_cfs_throttled_seconds_total{\n        k8s_namespace_name=\"$namespace\",\n        k8s_pod_name=\"$pod\",\n        k8s_container_name!=\"\",\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        env=~\"$env\"\n      },\n      \"container\",\n      \"$1\",\n      \"k8s_container_name\",\n      \"(.+)\"\n    )[$__rate_interval]\n  )\n) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "OOM Events by Container",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    container_oom_events_total{\n      k8s_namespace_name=\"$namespace\",\n      k8s_pod_name=\"$pod\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (k8s_container_name) > 0",
     "legendFormat": "{{ k8s_container_name }}"
    }
   ]
  },
  {
   "title": "Container Restarts by Container",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    kube_pod_container_status_restarts_total{\n      namespace=\"$namespace\",\n      pod=\"$pod\", \n      container!=\"\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (container) > 0",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Pods with Container Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{\n  reason=~\"ErrImagePull|ImagePullBackOff|CrashLoopBackOff\", \n  app=~\"$app\", \n  region=~\"$region\", \n  cluster_id=~\"$cluster_id\", \n  env=~\"$env\"\n} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unscheduled Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "kube_pod_status_scheduled{\n  condition=\"false\", \n  app=~\"$app\", \n  region=~\"$region\", \n  cluster_id=~\"$cluster_id\", \n  env=~\"$env\"\n} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Network I/O ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_pod_network_io_bytes_total{\n      direction=\"receive\", \n      k8s_namespace_name=\"$namespace\", \n      k8s_pod_name=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Input"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_pod_network_io_bytes_total{\n      direction=\"transmit\", \n      k8s_namespace_name=\"$namespace\", \n      k8s_pod_name=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Network Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    k8s_pod_network_errors_total{\n      direction=\"receive\", \n      k8s_namespace_name=\"$namespace\", \n      k8s_pod_name=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Input"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    k8s_pod_network_errors_total{\n      direction=\"transmit\", \n      k8s_namespace_name=\"$namespace\", \n      k8s_pod_name=\"$pod\", \n      app=~\"$app\", \n      region=~\"$region\", \n      cluster_id=~\"$cluster_id\", \n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Output"
    }
   ]
  }
 ]
}