{
 "title": "API Server",
 "description": "Kubernetes Dashboard - a fork from dotdc/grafana-dashboards-kubernetes/k8s-system-api-server.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(apiserver_request_total,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(apiserver_request_total{app=~\"$app\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(apiserver_request_total{app=~\"$app\", region=~\"$region\"},cluster_id)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(apiserver_request_total{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},env)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  {
   "title": "API Server - Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{\n  job=\"kubernetes-apiserver\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Requests by Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (\n  ${rate_func}(\n    apiserver_request_total{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Deprecated Kubernetes Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "apiserver_requested_deprecated_apis{\n  job=\"kubernetes-apiserver\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}"
    }
   ]
  },
  {
   "title": "HTTP Requests Latency by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    apiserver_request_duration_seconds_sum{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (instance)\n/\nsum(\n  ${rate_func}(\n    apiserver_request_duration_seconds_count{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Requests by Verb",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (verb) (\n  ${rate_func}(\n    apiserver_request_total{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "{{ verb}}"
    }
   ]
  },
  {
   "title": "Errors by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (\n  ${rate_func}(\n    apiserver_request_total{\n      code=~\"5..\",\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)\n/\nsum by(instance) (\n  ${rate_func}(\n    apiserver_request_total{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Requests Latency by Verb",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    apiserver_request_duration_seconds_sum{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (verb)\n/\nsum(\n  ${rate_func}(\n    apiserver_request_duration_seconds_count{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "Stacked HTTP Requests by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    apiserver_request_total{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Errors by Verb",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(verb) (\n  ${rate_func}(\n    apiserver_request_total{\n      code=~\"5..\",\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)\n/\nsum by(verb) (\n  ${rate_func}(\n    apiserver_request_total{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${rate_func}(\n  process_cpu_seconds_total{\n    job=\"kubernetes-apiserver\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }[$__rate_interval]\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RAM Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{\n  job=\"kubernetes-apiserver\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Work Queue by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    workqueue_depth{\n      job=\"kubernetes-apiserver\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}