{
 "title": "CoreDNS",
 "description": "Kubernetes Dashboard - a fork from dotdc/grafana-dashboards-kubernetes/k8s-system-coredns.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(coredns_dns_requests_total,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(coredns_dns_requests_total{app=~\"$app\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(coredns_dns_requests_total{app=~\"$app\", region=~\"$region\"},cluster_id)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(coredns_dns_requests_total{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},env)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "label_values(coredns_dns_requests_total{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", env=~\"$env\"},proto)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  {
   "title": "CoreDNS - Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{\n  job=\"coredns\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${rate_func}(\n  process_cpu_seconds_total{\n    job=\"coredns\",\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }[$__rate_interval]\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RAM Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{\n  job=\"coredns\",\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  env=~\"$env\"\n}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DNS Requests ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    coredns_dns_requests_total{\n      proto=\"$protocol\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Packet Size Average ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    coredns_dns_request_size_bytes_sum{\n      proto=\"$protocol\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (proto) / sum(\n  ${rate_func}(\n    coredns_dns_request_size_bytes_count{\n      proto=\"$protocol\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (proto)",
     "legendFormat": "Packet Size"
    }
   ]
  },
  {
   "title": "Requests by Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    coredns_dns_requests_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Requests by Return Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    coredns_dns_responses_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "Forward Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    coredns_proxy_request_duration_seconds_count{\n      proxy_name=\"forward\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    coredns_proxy_request_duration_seconds_count{\n      proxy_name=\"forward\",\n      rcode=~\"SERVFAIL|REFUSED\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "Cache Hits / Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    coredns_cache_hits_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(\n  ${rate_func}(\n    coredns_cache_misses_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  coredns_cache_entries{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "DNS Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    coredns_dns_request_duration_seconds_bucket{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DNS Request Size",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    coredns_dns_request_size_bytes_bucket{\n      le!=\"0\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DNS Response Size",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    coredns_dns_response_size_bytes_bucket{\n      le!=\"0\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}