{
 "title": "Traefik",
 "description": "Traefik Dashboard - a fork from 17347 (ID).",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(traefik_service_requests_total,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(traefik_service_requests_total{app=~\"$app\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(traefik_service_requests_total{app=~\"$app\", region=~\"$region\"},cluster_id)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(traefik_service_requests_total{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},env)"
    }
   },
   {
    "name": "entrypoint",
    "label": "Entrypoint",
    "query": {
     "query": "label_values(traefik_entrypoint_requests_total{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", env=~\"$env\"},entrypoint)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", env=~\"$env\"},service)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "label_values(traefik_service_requests_total{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", env=~\"$env\"},protocol)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(\n  traefik_config_reloads_total{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    traefik_entrypoint_requests_total{\n      entrypoint=~\"$entrypoint\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "timeseries",
   "description": "https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(\n  sum(\n    ${rate_func}(\n      traefik_entrypoint_request_duration_seconds_bucket{\n        le=\"0.3\",\n        code=\"200\",\n        entrypoint=~\"$entrypoint\",\n        app=~\"$app\",\n      region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        env=~\"$env\"\n      }[$__rate_interval]\n    )\n  ) by (method) +\n  sum(\n    ${rate_func}(\n      traefik_entrypoint_request_duration_seconds_bucket{\n        le=\"1.2\",\n        code=\"200\",\n        entrypoint=~\"$entrypoint\",\n        app=~\"$app\",\n      region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        env=~\"$env\"\n      }[$__rate_interval]\n    )\n  ) by (method)\n) / 2 /\n(\n  sum(\n    ${rate_func}(\n      traefik_entrypoint_request_duration_seconds_count{\n        code=\"200\",\n        entrypoint=~\"$entrypoint\",\n        app=~\"$app\",\n      region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        env=~\"$env\"\n      }[$__rate_interval]\n    )\n  ) by (method)\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http Code ",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    traefik_service_requests_total{\n      service=~\"$service\",\n      protocol=~\"$protocol\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) by (method, code)",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Top Slow Services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  label_replace(\n    traefik_service_request_duration_seconds_sum{\n      service=~\"$service\",\n      protocol=~\"$protocol\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    } /\n    traefik_service_request_duration_seconds_count{\n      service=~\"$service\",\n      protocol=~\"$protocol\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    },\n    \"service\",\n    \"$1\",\n    \"service\",\n    \"([^@]+)@.*\"\n  )\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Most Requested Services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  label_replace(\n    (\n      sum by (service, code) (\n        ${rate_func}(\n          traefik_service_requests_total{\n            service=~\"$service\",\n            protocol=~\"$protocol\",\n            app=~\"$app\",\n      region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            env=~\"$env\"\n          }[$__rate_interval]\n        )\n      ) > 0\n    ),\n    \"service\",\n    \"$1\",\n    \"service\",\n    \"([^@]+)@.*\"\n  )\n)",
     "legendFormat": "[{{code}}] on {{service}}"
    }
   ]
  },
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Services Failing SLO of 1200ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  1 - (\n    sum by (service) (\n      ${rate_func}(\n        traefik_service_request_duration_seconds_bucket{\n          le=\"1.2\",\n          service=~\"$service\",\n          app=~\"$app\",\n      region=~\"$region\",\n          cluster_id=~\"$cluster_id\",\n          env=~\"$env\"\n        }[$__rate_interval]\n      )\n    ) /\n    sum by (service) (\n      ${rate_func}(\n        traefik_service_request_duration_seconds_count{\n          service=~\"$service\",\n          app=~\"$app\",\n      region=~\"$region\",\n          cluster_id=~\"$cluster_id\",\n          env=~\"$env\"\n        }[$__rate_interval]\n      )\n    )\n  ) > 0,\n  \"service\",\n  \"$1\",\n  \"service\",\n  \"([^@]+)@.*\"\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services Failing SLO of 300ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  1 - (\n    sum by (service) (\n      ${rate_func}(\n        traefik_service_request_duration_seconds_bucket{\n          le=\"0.3\",\n          service=~\"$service\",\n          app=~\"$app\",\n      region=~\"$region\",\n          cluster_id=~\"$cluster_id\",\n          env=~\"$env\"\n        }[$__rate_interval]\n      )\n    ) /\n    sum by (service) (\n      ${rate_func}(\n        traefik_service_request_duration_seconds_count{\n          service=~\"$service\",\n          app=~\"$app\",\n      region=~\"$region\",\n          cluster_id=~\"$cluster_id\",\n          env=~\"$env\"\n        }[$__rate_interval]\n      )\n    )\n  ) > 0,\n  \"service\",\n  \"$1\",\n  \"service\",\n  \"([^@]+)@.*\"\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "2xx Codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  label_replace(\n    (\n      sum by (service, method, code) (\n        ${rate_func}(\n          traefik_service_requests_total{\n            service=~\"$service\",\n            code=~\"2..\",\n            protocol=~\"$protocol\",\n            app=~\"$app\",\n      region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            env=~\"$env\"\n          }[$__rate_interval]\n        )\n      ) > 0\n    ),\n    \"service\",\n    \"$1\",\n    \"service\",\n    \"([^@]+)@.*\"\n  )\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "5xx Codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  label_replace(\n    (\n      sum by (service, method, code) (\n        ${rate_func}(\n          traefik_service_requests_total{\n            service=~\"$service\",\n            code=~\"5..\",\n            protocol=~\"$protocol\",\n            app=~\"$app\",\n      region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            env=~\"$env\"\n          }[$__rate_interval]\n        )\n      ) > 0\n    ),\n    \"service\",\n    \"$1\",\n    \"service\",\n    \"([^@]+)@.*\"\n  )\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Other HTTP Codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  label_replace(\n    (\n      sum by (service, method, code) (\n        ${rate_func}(\n          traefik_service_requests_total{\n            service=~\"$service\",\n            code!~\"2..|5..\",\n            protocol=~\"$protocol\",\n            app=~\"$app\",\n      region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            env=~\"$env\"\n          }[$__rate_interval]\n        )\n      ) > 0\n    ),\n    \"service\",\n    \"$1\",\n    \"service\",\n    \"([^@]+)@.*\"\n  )\n)",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  label_replace(\n    (\n      sum by (service, method) (\n        ${rate_func}(\n          traefik_service_requests_bytes_total{\n            service=~\"$service\",\n            protocol=~\"$protocol\",\n            app=~\"$app\",\n      region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            env=~\"$env\"\n          }[$__rate_interval]\n        )\n      ) > 0\n    ),\n    \"service\",\n    \"$1\",\n    \"service\",\n    \"([^@]+)@.*\"\n  )\n)",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  },
  {
   "title": "Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  label_replace(\n    (\n      sum by (service, method) (\n        ${rate_func}(\n          traefik_service_responses_bytes_total{\n            service=~\"$service\",\n            protocol=~\"$protocol\",\n            app=~\"$app\",\n      region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            env=~\"$env\"\n          }[$__rate_interval]\n        )\n      ) > 0\n    ),\n    \"service\",\n    \"$1\",\n    \"service\",\n    \"([^@]+)@.*\"\n  )\n)",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  }
 ]
}