{
 "title": "MongoDB",
 "description": "MongoDB Dashboard - a fork from 14997 (ID).",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(mongodb_connections,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(mongodb_connections{app=~\"$app\"}, region)"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "label_values(mongodb_connections{app=~\"$app\", region=~\"$region\"}, cluster_id)"
   },
   {
    "name": "k8s_node_name",
    "label": "Node",
    "query": {
     "query": "label_values(mongodb_connections{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},k8s_node_name)"
    }
   },
   {
    "name": "k8s_pod_name",
    "label": "Pod",
    "query": {
     "query": "label_values(mongodb_connections{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", k8s_node_name=~\"$k8s_node_name\"},k8s_pod_name)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(mongodb_connections{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", k8s_node_name=~\"$k8s_node_name\", k8s_pod_name=~\"$k8s_pod_name\"},env)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n    mongodb_instance_uptime_seconds{\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n    }\n)",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Connection Saturation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    mongodb_connections{\n        state=\"current\",\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n    }\n  ) \n  / \n  sum(\n    mongodb_connections{\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n    }\n  )\n)",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    mongodb_connections{\n        state=\"current\",\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n    }\n)",
     "legendFormat": "Open Connections"
    }
   ]
  },
  {
   "title": "Replica Set Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(\n    mongodb_mongod_replset_number_of_members{\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n    }\n)",
     "legendFormat": "Members Count"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (\n    ${rate_func}(\n        mongodb_op_counters_total{\n            app=~\"$app\",\n            region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            k8s_node_name=~\"$k8s_node_name\",\n            k8s_pod_name=~\"$k8s_pod_name\",\n            env=~\"$env\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (state) (\n    ${rate_func}(\n        mongodb_mongod_metrics_document_total{\n            app=~\"$app\",\n            region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            k8s_node_name=~\"$k8s_node_name\",\n            k8s_pod_name=~\"$k8s_pod_name\",\n            env=~\"$env\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Read Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    mongodb_mongod_op_latencies_latency_total{\n      type=\"read\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) \n/ \nsum(\n  ${rate_func}(\n    mongodb_mongod_op_latencies_ops_total{\n      type=\"read\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) / 1000",
     "legendFormat": "Read Latency"
    }
   ]
  },
  {
   "title": "Write Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    mongodb_mongod_op_latencies_latency_total{\n      type=\"write\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) \n/ \nsum(\n  ${rate_func}(\n    mongodb_mongod_op_latencies_ops_total{\n      type=\"write\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n) / 1000",
     "legendFormat": "Write Latency"
    }
   ]
  },
  { "title": "Replica Set Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Member State (1=PRIMARY, 2=SECONDARY, 7=ARBITER)",
   "type": "barchart",
   "description": "See which node is currently acting as the primary, secondary, arbiter",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (member_idx, member_state) (\n    mongodb_rs_members_state{\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n    }\n)",
     "legendFormat": "{{member_state}} - {{member_idx}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "RAM Utilization (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "avg by (type) (\n    mongodb_memory{\n        type=~\"resident|virtual\",\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n    }\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    mongodb_ss_network_bytesIn{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Input"
    },
    {
     "expr": "- sum(\n  ${rate_func}(\n    mongodb_ss_network_bytesOut{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "Output"
    }
   ]
  },
  { "title": "Oplog Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Oplog Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "max(\n    ${rate_func}(\n        mongodb_mongod_replset_oplog_head_timestamp{\n            app=~\"$app\",\n            region=~\"$region\",\n            cluster_id=~\"$cluster_id\",\n            k8s_node_name=~\"$k8s_node_name\",\n            k8s_pod_name=~\"$k8s_pod_name\",\n            env=~\"$env\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "Oplog Lag"
    }
   ]
  }
 ]
}