{
 "title": "Redis",
 "description": "Redis Dashboard - a fork from 18345 (ID).",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(redis_connected_clients,app)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(redis_connected_clients{app=~\"$app\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_connected_clients{app=~\"$app\", region=~\"$region\"},cluster_id)"
    }
   },
   {
    "name": "k8s_node_name",
    "label": "Node",
    "query": {
     "query": "label_values(redis_connected_clients{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\"},k8s_node_name)"
    }
   },
   {
    "name": "k8s_pod_name",
    "label": "Pod",
    "query": {
     "query": "label_values(redis_connected_clients{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", k8s_node_name=~\"$k8s_node_name\"},k8s_pod_name)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(redis_connected_clients{app=~\"$app\", region=~\"$region\", cluster_id=~\"$cluster_id\", k8s_node_name=~\"$k8s_node_name\", k8s_pod_name=~\"$k8s_pod_name\"},env)"
    }
   },
   { "name": "rate_func", "label": "Mode", "query": "Overview : rate, Debug : irate" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(\n  redis_uptime_in_seconds{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Connection Saturation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    redis_connected_clients{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }\n  )\n  /\n  sum(\n    redis_config_maxclients{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }\n  )\n)",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  redis_connected_clients{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Open Connections"
    }
   ]
  },
  {
   "title": "Number of keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  redis_db_keys{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Keys"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    redis_commands_processed_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "Slow Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    redis_slowlog_last_id{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Slow Operations"
    }
   ]
  },
  {
   "title": "Read Workload",
   "type": "timeseries",
   "description": "Since we are measuring sum(rate(...seconds_total)), the unit is \"seconds per second\". This can be conceptually tricky, but it's powerful:\n\n    0.1s: This Workload spends 10% of its time processing this type of workload.\n\n    1.0s: This workload is consuming 1 full CPU core's worth of time continuously.\n\n    2.5s: This workload is consuming 2.5 cores (total, across all the nodes).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    redis_commands_duration_seconds_total{\n      cmd=~\"get|mget|hget|hgetall|lrange|smembers|scard|zrange|zcard|exists|ttl|ping|hexists|info\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Read Workload"
    }
   ]
  },
  {
   "title": "Write Workload",
   "type": "timeseries",
   "description": "Since we are measuring sum(rate(...seconds_total)), the unit is \"seconds per second\". This can be conceptually tricky, but it's powerful:\n\n    0.1s: This Workload spends 10% of its time processing this type of workload.\n\n    1.0s: This workload is consuming 1 full CPU core's worth of time continuously.\n\n    2.5s: This workload is consuming 2.5 cores (total, across all the nodes).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    redis_commands_duration_seconds_total{\n      cmd=~\"set|mset|setex|setnx|hset|hdel|lpush|rpush|sadd|srem|zadd|zrem|del|expire|incr|decr|publish\",\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Write Workload"
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    redis_keyspace_hits_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)\n/\n(\n  sum(\n    rate(\n      redis_keyspace_hits_total{\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n      }[$__rate_interval]\n    )\n  )\n  +\n  sum(\n    rate(\n      redis_keyspace_misses_total{\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "Hit"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    redis_commands_duration_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  ${rate_func}(\n    redis_commands_processed_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Latency"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "RAM Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  redis_memory_used_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Used Memory "
    },
    {
     "expr": "sum(\n  redis_memory_used_peak_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Used Memory Peak"
    },
    {
     "expr": "sum(\n  redis_memory_used_lua_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Used Memory Lua"
    },
    {
     "expr": "sum(\n  redis_memory_used_dataset_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Used Memory Dataset"
    },
    {
     "expr": "sum(\n  redis_memory_used_overhead_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Used Memory Overhead"
    },
    {
     "expr": "sum(\n  redis_memory_used_rss_bytes{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Used Memory Rss"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    redis_net_input_bytes_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Input"
    },
    {
     "expr": "-sum(\n  rate(\n    redis_net_output_bytes_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "User CPU: This represents time the processor spends executing your application code.\n\n    High User CPU means your application is busy processing data.\n\nSystem CPU: This represents time the processor spends in the Kernel.\n\n    This is overhead from the Operating System, primarily handling Network I/O (reading/writing TCP packets) and Disk I/O. High System CPU often indicates a bottleneck in networking or disk speed.\n\nNote on \"Children\": This metric includes CPU used by Background Processes (Children). In Redis, these child processes are spawned to handle persistence tasks like RDB Snapshotting or AOF Rewriting. Spikes in this graph often correlate with backup operations.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  ${rate_func}(\n    redis_cpu_sys_children_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n  +\n  ${rate_func}(\n    redis_cpu_sys_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "System"
    },
    {
     "expr": "sum(\n  rate(\n    redis_cpu_user_children_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n  +\n  rate(\n    redis_cpu_user_seconds_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      k8s_node_name=~\"$k8s_node_name\",\n      k8s_pod_name=~\"$k8s_pod_name\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "User"
    }
   ]
  },
  { "title": "Additional Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Expired / Evicted keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(\n    increase(\n      redis_expired_keys_total{\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n      }[$__rate_interval]\n    )\n  )\n) \n/ \nsum(redis_db_keys{\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  k8s_node_name=~\"$k8s_node_name\",\n  k8s_pod_name=~\"$k8s_pod_name\",\n  env=~\"$env\"\n  }\n)",
     "legendFormat": "Expired"
    },
    {
     "expr": "(\n  sum(\n    increase(\n      redis_evicted_keys_total{\n        app=~\"$app\",\n        region=~\"$region\",\n        cluster_id=~\"$cluster_id\",\n        k8s_node_name=~\"$k8s_node_name\",\n        k8s_pod_name=~\"$k8s_pod_name\",\n        env=~\"$env\"\n      }[$__rate_interval]\n    )\n  )\n) \n/ \nsum(redis_db_keys{\n  app=~\"$app\",\n  region=~\"$region\",\n  cluster_id=~\"$cluster_id\",\n  k8s_node_name=~\"$k8s_node_name\",\n  k8s_pod_name=~\"$k8s_pod_name\",\n  env=~\"$env\"\n  }\n)",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Blocked and Rejected clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  redis_blocked_clients{\n    app=~\"$app\",\n    region=~\"$region\",\n    cluster_id=~\"$cluster_id\",\n    k8s_node_name=~\"$k8s_node_name\",\n    k8s_pod_name=~\"$k8s_pod_name\",\n    env=~\"$env\"\n  }\n)",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum(\n  ${rate_func}(\n    redis_rejected_connections_total{\n      app=~\"$app\",\n      region=~\"$region\",\n      cluster_id=~\"$cluster_id\",\n      env=~\"$env\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Rejected"
    }
   ]
  }
 ]
}